<img class="float-center hide-for-small-only"
     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/cms/banner/leasing-mietkauf-banner.png'; ?>"
     alt="Leasing Mietkauf Banner"/>
<h1 class="h3"><?php echo $this->__('Ihre schnelle und g&uuml;nstige Finanzierung: Leasing oder Mietkauf') ?></h1>
<p class="h4" id="formular"><?php echo $this->__('Leasing/Mietkauf-Formular') ?></p>
<form action="<?php echo Mage::getBaseUrl() . 'leasing-mietkauf/index/post/'; ?>" method="post" id="leasing-form"
      data-abide novalidate>
    <input type="hidden" name="wcrl" value="<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>"/>
    <input type="hidden" name="form_key"
           value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
    <div data-abide-error class="alert callout" style="display: none;">
        <p><i class="fi-alert"></i><?php echo $this->__('There are some errors in your form.') ?></p>
    </div>
    <div class="grid-x grid-margin-x grid-padding-x">
        <div class="small-12 cell">
            <p><?php echo $this->__('Gern unterbreiten wir Ihnen ein kostenfreies, pers&ouml;nliches, unverbindliches Angebot. Bitte f&uuml;llen Sie hierzu das folgende Formular aus. Sobald Ihre Anfrage bei uns eingetroffen ist, setzen wir uns umgehend mit Ihnen in Verbindung.') ?></p>
            <hr>
            <fieldset>
                <legend><?php echo $this->__('Ich interessiere mich für') ?></legend>
                <input type="radio" name="type" value="leasing" id="leasing" required>
                <label for="leasing"><?php echo $this->__('Leasing') ?></label>
                <input type="radio" name="type" value="mietkauf" id="mietkauf" required>
                <label for="mietkauf"><?php echo $this->__('Mietkauf') ?></label>
                <span class="form-error"><?php echo $this->__('required') ?></span>
            </fieldset>
        </div>
        <div class="small-12 medium-4 cell">
            <label for="object"><?php echo $this->__('Name der gewünschten Leasing/Mietkauf-Objekte') ?>
                <small><?php echo $this->__('required') ?></small>
                <textarea id="object" name="object" placeholder="" required></textarea>
                <span class="form-error"><?php echo $this->__('required') ?></span>
            </label>
            <label for="term"><?php echo $this->__('Wählen Sie eine Vertragslaufzeit') ?>
                <select id="term" name="term" required>
                    <option value=""></option>
                    <option value="15m"><?php echo $this->__('15 Monate') ?></option>
                    <option value="24m"><?php echo $this->__('24 Monate') ?></option>
                    <option value="30m"><?php echo $this->__('30 Monate') ?></option>
                    <option value="36m"><?php echo $this->__('36 Monate') ?></option>
                    <option value="42m"><?php echo $this->__('42 Monate') ?></option>
                    <option value="48m"><?php echo $this->__('48 Monate') ?></option>
                    <option value="54m"><?php echo $this->__('54 Monate') ?></option>
                    <option value="60m"><?php echo $this->__('60 Monate') ?></option>
                    <option value="72m"><?php echo $this->__('72 Monate') ?></option>
                </select>
            </label>
        </div>
        <div class="small-12 medium-4 cell">
            <label for="company"><?php echo $this->__('Unternehmen') ?>
                <input id="company" name="company" type="text">
            </label>
            <label for="contact"><?php echo $this->__('Ansprechpartner') ?>
                <small><?php echo $this->__('required') ?></small>
                <input id="contact" name="contact" type="text" required>
                <span class="form-error"><?php echo $this->__('required') ?></span>
            </label>
            <label for="mail"><?php echo $this->__('E-Mail') ?>
                <input id="mail" name="mail" type="email">
            </label>
            <label for="street"><?php echo $this->__('Straße') ?>
                <input id="street" name="street" type="text">
            </label>
        </div>
        <div class="small-12 medium-4 cell">
            <label for="zip"><?php echo $this->__('Postleitzahl') ?>
                <input id="zip" name="zip" type="text">
            </label>
            <label for="city"><?php echo $this->__('Ort') ?>
                <input id="city" name="city" type="text">
            </label>
            <label for="fon"><?php echo $this->__('Telefon') ?>
                <small><?php echo $this->__('required') ?></small>
                <input id="fon" name="fon" type="text" required>
                <span class="form-error"><?php echo $this->__('required') ?></span>
            </label>
            <label for="remarks"><?php echo $this->__('Ihre persönlichen Anmerkungen') ?>
                <textarea id="remarks" name="remarks" placeholder=""></textarea>
            </label>
        </div>
        <div class="small-12 cell margin-bottom-2">
            <div class="grid-x grid-margin-x grid-padding-x">
                <div class="small-1 cell"><input id="bdsg" name="bdsg" type="checkbox" value="accept" required></div>
                <div class="small-11 cell"><label
                            for="bdsg"><?php echo $this->__('Ich stimme zu, dass meine Angaben aus dem Kontaktformular zur Beantwortung meiner Anfrage erhoben und verarbeitet werden. Die von Ihnen im Kontaktformular eingegebenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihrer Anfrage). Hinweis: Sie können Ihre Einwilligung jederzeit für die Zukunft per E-Mail an datenschutz@newgastroline.de widerrufen. Detaillierte Informationen zum Umgang mit Nutzerdaten finden Sie in unserer <a href="%s">Datenschutzerklärung</a>.', Mage::getUrl('datenschutz')) ?></label>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-container">
        <div class="grid-x grid-margin-x">
            <fieldset class="cell large-6">
                <button class="button hollow" type="reset" value="Reset">Anfrage zurücksetzen</button>
            </fieldset>
            <fieldset class="cell large-6">
                <button class="button float-right" type="submit" value="Submit">Anfrage versenden</button>
            </fieldset>
        </div>
    </div>
</form>
<hr>
<p class="h4">Finanzierung schafft Mehrwert</p>
<p><strong>Sie erhalten die Spielräume, die Sie benötigen.</strong><br>Unsere Angebote sind auf Sie zugeschnittene
    Lösungen. Vertragsinhalte zu Raten, Laufzeiten etc. werden nach Ihren Bedürfnissen festgelegt.</p>
<p><strong>Sie behalten stets den Überblick über Ihre Verpflichtung.</strong><br>Durch die konstanten Monatsraten
    kalkulieren Sie dauerhaft sicher.</p>
<p><strong>Sie sparen Zeit – wir prüfen innerhalb sehr kurzer Zeit.</strong><br>Eine Zusage erhalten Sie
    gegebenenfalls innerhalb weniger Minuten. Anschließend übernehmen wir alle Formalitäten für Sie.</p>
<p class="h4">Leasing oder Mietkauf?</p>
<p>Wenn Sie bei uns ein Produkt über einen Mietkauf finanzieren, sind Sie am Ende der Vertragslaufzeit der
    Eigentümer dieses Produktes. Im Gegensatz dazu bezahlen Sie beim Leasing für dessen Nutzung. Eigentümer bleibt
    in diesem Fall die Leasing-Gesellschaft.</p>
<p class="h4">Warum lohnt sich Leasing?</p>
<ul>
    <li>Geleaste Produkte erscheinen nicht in Ihrer Bilanz (Bilanzneutralität). Lediglich die Raten werden von Ihnen
        als Betriebsausgaben verbucht.
    </li>
    <li>Diese Betriebsausgaben sind steuerlich voll absetzbar – ein klarer Steuervorteil für Sie.</li>
    <li>Leasing-Raten bleiben konstant. Sie werden weder mittel- noch langfristig von fallenden oder steigenden
        Zinsen beeinflusst. Sie erhalten damit Kalkulations- und Planungssicherheit.
    </li>
    <li>Sie müssen nicht in Vorleistung gehen. Sie zahlen monatliche Raten, während Sie das Produkt nutzen, um Ihre
        Erträge zu erwirtschaften („Pay as you earn“).
    </li>
    <li>Da es sich um keinen Kredit handelt, wird der Kreditrahmen bei Ihrer Bank geschont; Ihre Bonität ändert sich
        dadurch nicht.
    </li>
    <li>Die Laufzeit des Leasing-Vertrages beträgt für gewöhnlich zwischen 40 und 90 Prozent der Abschreibungsdauer
        laut AfA-Tabelle (Abschreibungstabelle für allgemein verwendbare Anlagegüter).
    </li>
</ul>
<p class="h4">Was sind die Unterschiede zum Mietkauf?</p>
<ul>
    <li>Erst am Ende der vertraglich vereinbarten Zeit sind Sie bei einem Mietkauf der (zivilrechtliche) Eigentümer
        des Produktes.
    </li>
    <li>Aus steuerlicher Sicht ist das Produkt jedoch Ihr (wirtschaftliches) Eigentum, und zwar bereits ab der
        ersten Rate. Die aus der Gesamtsumme resultierende Umsatzsteuer ist durch Sie zu begleichen.
    </li>
    <li>Aber: Das Produkt zählt ab der ersten Rate zu Ihrem Anlagevermögen. Sie können es selbst bilanzieren,
        Abschreibungen verrechnen und gegebenenfalls Fördermittel oder Investitionszulagen für die Anschaffung
        beantragen.
    </li>
    <li>Vertragslaufzeiten können beim Vertragsabschluss flexibler ausgestaltet werden.</li>
    <li>Eine Kündigung ist immer möglich, wenn Sie die Abschlusszahlung leisten.</li>
</ul>
<p class="h4">Wie verläuft die Finanzierung?</p>
<div class="grid-x grid-margin-x grid-padding-x align-middle">
    <div class="small-12 medium-9 cell">
        <ol>
            <li>Sie fordern bei uns ein Angebot über Ihren Warenbedarf und die gewünschte Finanzierungsart an.</li>
            <li>Wir erstellen für Sie ein individuelles Angebot und stellen mit Ihnen den Mietkauf- bzw.
                Leasing-Antrag.
            </li>
            <li>Unser Finanzpartner prüft Ihre Bonität, das Investitionsobjekt (die Ware) und den Antrag.</li>
            <li>Sie erhalten eine Auftragsbestätigung in Verbindung mit einem Leasing- oder Mietkauf-Vertrag sowie ein
                Formular für die Übernahmebestätigung. Den Vertrag senden Sie unterschrieben an uns zurück.
            </li>
            <li>Wir liefern Ihnen die bestellte Ware.</li>
            <li>Sie bestätigen dem Finanzpartner den Erhalt der Ware mit der rechtsverbindlich unterschriebenen
                Übernahmebestätigung.
            </li>
            <li>Sie erhalten abschließende Informationen über das Vertragsverhältnis, wie Vertragslaufzeiten,
                Rechnungsbetrag, Raten; zudem eine Zahlungsaufforderung.
            </li>
            <li>Die Raten werden in der Regel mit Ihrer Einzugsermächtigung von Ihrem Konto eingezogen.</li>
        </ol>
    </div>
    <div class="small-12 medium-3 cell">
        <img class="thumbnail"
             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/cms/Bilder/2017-05-29_leasingvertrag_1920.jpg'; ?>"
             alt="Leasingvertrag Beispiel"/>
        <p class="text-center">Wir übernehmen für Sie alle Formalitäten.</p>
    </div>
</div>
<p class="h4">Welche Voraussetzungen muss ich für Leasing oder Mietkauf erfüllen?</p>
<ul>
    <li>Ihr Gewerbe ist in Deutschland gemeldet.</li>
    <li>Ihr Unternehmen besteht seit mindestens zwei Jahren.</li>
    <li>Sie sind seit mindestens zwei Jahren im selben Gewerbe tätig.</li>
    <li>Der Finanzdienstleister (unser Partner) prüft erfolgreich Ihre Bonität.</li>
</ul>